# If we're in a preview environment, allow the preview ingressgateway to access us
{{ if and (ne "prod" .Release.Namespace) (ne "dev" .Release.Namespace) }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "allow-istio-ingressgateway-preview-ingress-skypilot"
spec:
  endpointSelector:
    matchLabels:
      retort/skypilot-ingress: "true"
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: istio-system
        app: istio-ingressgateway-preview
{{ end }}